{"name": "使用无效用户名登录", "status": "passed", "description": "测试使用无效用户名登录", "steps": [{"name": "发送登录请求", "status": "passed", "start": 1742985767893, "stop": 1742985767896}, {"name": "验证登录失败", "status": "passed", "start": 1742985767896, "stop": 1742985767896}], "attachments": [{"name": "stderr", "source": "550e8f60-00a8-4119-98be-a098b5836808-attachment.txt", "type": "text/plain"}], "start": 1742985767893, "stop": 1742985767896, "uuid": "a98d343f-9b2c-4851-a12d-dc425b0a239f", "historyId": "98b10f3205b684d85418cc30d76884bf", "testCaseId": "98b10f3205b684d85418cc30d76884bf", "fullName": "test_cases.api.test_demo_api.TestUserAPI#test_login_with_invalid_username", "labels": [{"name": "epic", "value": "API测试"}, {"name": "story", "value": "登录接口"}, {"name": "feature", "value": "用户管理"}, {"name": "parentSuite", "value": "test_cases.api"}, {"name": "suite", "value": "test_demo_api"}, {"name": "subSuite", "value": "TestUserAPI"}, {"name": "host", "value": "MacBook-Pro.local"}, {"name": "thread", "value": "38280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.api.test_demo_api"}]}