{"name": "使用无效用户名登录", "status": "passed", "description": "测试使用无效用户名登录", "steps": [{"name": "发送登录请求", "status": "passed", "start": 1742990119287, "stop": 1742990119289}, {"name": "验证登录失败", "status": "passed", "start": 1742990119289, "stop": 1742990119289}], "attachments": [{"name": "stderr", "source": "5e69b7f6-c8a5-44a9-aa6b-6e56a1782a7d-attachment.txt", "type": "text/plain"}], "start": 1742990119287, "stop": 1742990119289, "uuid": "09185dae-b336-40af-8657-6ae2b597da82", "historyId": "98b10f3205b684d85418cc30d76884bf", "testCaseId": "98b10f3205b684d85418cc30d76884bf", "fullName": "test_cases.api.test_demo_api.TestUserAPI#test_login_with_invalid_username", "labels": [{"name": "story", "value": "登录接口"}, {"name": "epic", "value": "API测试"}, {"name": "feature", "value": "用户管理"}, {"name": "parentSuite", "value": "test_cases.api"}, {"name": "suite", "value": "test_demo_api"}, {"name": "subSuite", "value": "TestUserAPI"}, {"name": "host", "value": "MacBook-Pro.local"}, {"name": "thread", "value": "59671-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.api.test_demo_api"}]}