{"name": "使用无效用户名登录", "status": "passed", "description": "测试使用无效用户名登录", "steps": [{"name": "发送登录请求", "status": "passed", "start": 1742985581984, "stop": 1742985581987}, {"name": "验证登录失败", "status": "passed", "start": 1742985581987, "stop": 1742985581987}], "attachments": [{"name": "stderr", "source": "ba1eef2e-1696-4dc1-a0e2-1d018ba2f4d3-attachment.txt", "type": "text/plain"}], "start": 1742985581984, "stop": 1742985581987, "uuid": "e81b59f7-1f80-4572-b6a3-f2125f98ec67", "historyId": "98b10f3205b684d85418cc30d76884bf", "testCaseId": "98b10f3205b684d85418cc30d76884bf", "fullName": "test_cases.api.test_demo_api.TestUserAPI#test_login_with_invalid_username", "labels": [{"name": "epic", "value": "API测试"}, {"name": "story", "value": "登录接口"}, {"name": "feature", "value": "用户管理"}, {"name": "parentSuite", "value": "test_cases.api"}, {"name": "suite", "value": "test_demo_api"}, {"name": "subSuite", "value": "TestUserAPI"}, {"name": "host", "value": "MacBook-Pro.local"}, {"name": "thread", "value": "35501-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.api.test_demo_api"}]}