{"name": "使用无效用户名登录", "status": "passed", "description": "测试使用无效用户名登录", "steps": [{"name": "发送登录请求", "status": "passed", "start": 1742989934233, "stop": 1742989934236}, {"name": "验证登录失败", "status": "passed", "start": 1742989934236, "stop": 1742989934236}], "attachments": [{"name": "stderr", "source": "f3338ace-1503-40a3-9761-e76f688c6438-attachment.txt", "type": "text/plain"}], "start": 1742989934233, "stop": 1742989934236, "uuid": "74a4e0b6-38e6-4974-8ab5-a7ad8cc8bae5", "historyId": "98b10f3205b684d85418cc30d76884bf", "testCaseId": "98b10f3205b684d85418cc30d76884bf", "fullName": "test_cases.api.test_demo_api.TestUserAPI#test_login_with_invalid_username", "labels": [{"name": "story", "value": "登录接口"}, {"name": "feature", "value": "用户管理"}, {"name": "epic", "value": "API测试"}, {"name": "parentSuite", "value": "test_cases.api"}, {"name": "suite", "value": "test_demo_api"}, {"name": "subSuite", "value": "TestUserAPI"}, {"name": "host", "value": "MacBook-Pro.local"}, {"name": "thread", "value": "56045-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.api.test_demo_api"}]}