{"name": "使用无效用户名登录", "status": "passed", "description": "测试使用无效用户名登录", "steps": [{"name": "发送登录请求", "status": "passed", "start": 1742985799809, "stop": 1742985799812}, {"name": "验证登录失败", "status": "passed", "start": 1742985799812, "stop": 1742985799812}], "attachments": [{"name": "stderr", "source": "02bda456-6d29-47d0-8564-b9481776ba18-attachment.txt", "type": "text/plain"}], "start": 1742985799809, "stop": 1742985799812, "uuid": "f2daac27-bd37-419e-b69a-8fcd974b2260", "historyId": "98b10f3205b684d85418cc30d76884bf", "testCaseId": "98b10f3205b684d85418cc30d76884bf", "fullName": "test_cases.api.test_demo_api.TestUserAPI#test_login_with_invalid_username", "labels": [{"name": "feature", "value": "用户管理"}, {"name": "story", "value": "登录接口"}, {"name": "epic", "value": "API测试"}, {"name": "parentSuite", "value": "test_cases.api"}, {"name": "suite", "value": "test_demo_api"}, {"name": "subSuite", "value": "TestUserAPI"}, {"name": "host", "value": "MacBook-Pro.local"}, {"name": "thread", "value": "38765-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.api.test_demo_api"}]}