{"name": "使用无效用户名登录", "status": "passed", "description": "测试使用无效用户名登录", "steps": [{"name": "发送登录请求", "status": "passed", "start": 1742991641583, "stop": 1742991641585}, {"name": "验证登录失败", "status": "passed", "start": 1742991641585, "stop": 1742991641585}], "attachments": [{"name": "stderr", "source": "d20678a6-44a8-4aa9-9907-5357b6fb5ef4-attachment.txt", "type": "text/plain"}], "start": 1742991641583, "stop": 1742991641585, "uuid": "18482fb6-fa08-4bd2-9b50-524a3e815668", "historyId": "98b10f3205b684d85418cc30d76884bf", "testCaseId": "98b10f3205b684d85418cc30d76884bf", "fullName": "test_cases.api.test_demo_api.TestUserAPI#test_login_with_invalid_username", "labels": [{"name": "feature", "value": "用户管理"}, {"name": "story", "value": "登录接口"}, {"name": "epic", "value": "API测试"}, {"name": "parentSuite", "value": "test_cases.api"}, {"name": "suite", "value": "test_demo_api"}, {"name": "subSuite", "value": "TestUserAPI"}, {"name": "host", "value": "MacBook-Pro.local"}, {"name": "thread", "value": "78732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.api.test_demo_api"}]}